apiVersion: v1
kind: Service
metadata:
  name: splunk
  namespace: buildforge-monitoring
  labels:
    app: splunk
spec:
  selector:
    app: splunk
  ports:
    - name: web
      port: 8000
      targetPort: 8000
    - name: hec
      port: 8088
      targetPort: 8088
  type: ClusterIP
